name: lara_app
description: "A new Flutter project for LARA Emergency Assistance."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  # ML Kit Dependencies - Use these specific versions to avoid conflicts
  google_mlkit_face_detection: ^0.13.0
  google_mlkit_text_recognition: ^0.15.1
  google_mlkit_image_labeling: ^0.14.2
  google_mlkit_object_detection: ^0.15.1

  # Firebase Dependencies
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0
  
  firebase_storage: ^13.3.0
  
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  # Ensures Material Design icons (like the visibility eye) work
  uses-material-design: true

  # ASSETS CONFIGURATION (Points to your images folder)
  assets:
    - assets/

